### ISSUE TITLE
Support ActionController::API based controller

### ISSUE THREAD

**Issue by katsuma** [cookpad/trice#18]
We cannot use `requested_at` method at controllers based on `ActionController::API`.
Because trice current version does not check the controller.
- https://github.com/cookpad/trice/blob/master/lib/trice/controller_methods.rb#L11

We can use `requested_at` by these ad-hock instruction but you know it looks dirty hack 😎 

```ruby
class MyApiController < ActionController::API
  include Trice::ControllerMethods

  use Trice::ControllerMethods::RawReferenceTime
  config = Trice::ControllerMethods::StubConfiguration.new(Trice.support_requested_at_stubbing)
  prepend_around_action Trice::ControllerMethods::ReferenceTimeAssignment.new(config)
  helper_method :requested_at

end
```

How do you think to support `ActionController::API` ?

**Comment by eagletmt** [comment]
I'll look on it. `helper_method` seems unavailable in AC::API.

**Comment by katsuma** [comment]
> helper_method seems unavailable in AC::API.

agree 😅
